version: '3.8'
volumes:
        pipeline-zookeeper-a-volume:
                name: pipeline-zookeeper-a-volume
        pipeline-zookeeper-b-volume:
                name: pipeline-zookeeper-b-volume
        pipeline-zookeeper-c-volume:
                name: pipeline-zookeeper-c-volume

services:
        pipeline-zookeeper-a:
                image: pipeline-zookeeper
                container_name: pipeline-zookeeper-a
                restart: always
                hostname: pipeline-zookeeper-a
                environment:
                        MY_ID: 1
                volumes:
                        - pipeline-zookeeper-a-volume:/data

        pipeline-zookeeper-b:
                image: pipeline-zookeeper
                container_name: pipeline-zookeeper-b
                restart: always
                hostname: pipeline-zookeeper-b
                environment:
                        MY_ID: 2
                volumes:
                        - pipeline-zookeeper-b-volume:/data

        pipeline-zookeeper-c:
                image: pipeline-zookeeper
                container_name: pipeline-zookeeper-c
                restart: always
                hostname: pipeline-zookeeper-c
                environment:
                        MY_ID: 3
                volumes:
                        - pipeline-zookeeper-c-volume:/data

networks:
        out_net:
                driver: zoo2
